### ISSUE TITLE
SNMPv3 support?

### ISSUE THREAD

**Issue by lhadjchikh** [logstash-plugins/logstash-input-snmptrap#10]
From what I can tell, this plugin supports SNMPv1/v2 but not SNMPv3. Is that correct? Are there any plans to add v3 support? Thanks in advance for any info.

**Comment by fadecore** [comment]
+1

**Comment by jakommo** [comment]
:+1:

**Comment by gmoskovicz** [comment]
+1

**Comment by ppf2** [comment]
+1

**Comment by wenfli** [comment]
+1

**Comment by abiruth84** [comment]
Hi! 

any news on SNMPv3 support? We are having some troubles to get snmptraps from an HSM LUNA EFT and my guess is because these devices support only SNMPv3. I guess the issue I am having is exactly about the versions supported. 
I have installed logstash 2.4.1 in a windows 2012 server. I can simulate traps v1 successfully but I got this error last week when trying from my HSM. (At that time I had not imported the vendor MIB yet).

Error handling trap: 3
**D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/pdu.rb:65:in `decode_version'**
D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/pdu.rb:51:in `decode'
D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:707:in `process_traps'
org/jruby/RubyKernel.java:1479:in `loop'
D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:704:in `process_traps'
D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/snmp-1.2.0/lib/snmp/manager.rb:631:in `initialize'
Received data:
"0\x81\x8E\x02\x01\x030\x11\x02\x04hm}\xAE\x02\x03\x00\xFF\xE3\x04\x01\x00\x02\x01\x03\x04&0$\x04\r\x80\x00\x1F\x88\x80\xAC\xD1\xC4d\xBD\fmX\x02\x01\x01\x02\x02\x05\xC9\x04\bTestSNMP\x04\x00\x04\x000N\x04\r\x80\x00\x1F\x88\x80\xAC\xD1\xC4d\xBD\fmX\x04\x00\xA7;\x02\x04y\xD14\x95\x02\x01\x00\x02\x01\x000-0\x0F\x06\b+\x06\x01\x02\x01\x01\x03\x00C\x03\x02B\xCA0\x1A\x06\n+\x06\x01\x06\x03\x01\x01\x04\x01\x00\x06\f+\x06\x01\x04\x01\x81\xB8M\x03\x01\x01\v"
←[36mFlushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0x534d0ef1 @operations_mutex=#<Mutex:0x5d8afae8>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x59b56581>, @submit_proc=#<Proc:0x27b65f32@D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:57>, @logger=#<Cabin::Channel:0x2d61ac96 @metrics=#<Cabin::Metrics:0x5f8a5dd6 @metrics_lock=#<Mutex:0x7c980f9c>, @metrics={}, @channel=#<Cabin::Channel:0x2d61ac96 ...>>, @subscriber_lock=#<Mutex:0x69c280f2>, @level=:debug, @subscribers={13288=>#<Cabin::Subscriber:0x448e1447 @output=#<Cabin::Outputs::IO:0x78d617a5 @io=#<IO:fd 1>, @lock=#<Mutex:0x56edd5d>>, @options={}>}, @data={}>, @last_flush=2017-01-04 15:20:04 UTC, @flush_interval=1, @stopping=#<Concurrent::AtomicBoolean:0x705e1c24>, @buffer=[], @flush_thread=#<Thread:0x44460244 run>>", :interval=>1, :level=>:debug, :file=>"/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}←[0m
←[36mFlushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0x534d0ef1 @operations_mutex=#<Mutex:0x5d8afae8>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x59b56581>, @submit_proc=#<Proc:0x27b65f32@D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:57>, @logger=#<Cabin::Channel:0x2d61ac96 @metrics=#<Cabin::Metrics:0x5f8a5dd6 @metrics_lock=#<Mutex:0x7c980f9c>, @metrics={}, @channel=#<Cabin::Channel:0x2d61ac96 ...>>, @subscriber_lock=#<Mutex:0x69c280f2>, @level=:debug, @subscribers={13288=>#<Cabin::Subscriber:0x448e1447 @output=#<Cabin::Outputs::IO:0x78d617a5 @io=#<IO:fd 1>, @lock=#<Mutex:0x56edd5d>>, @options={}>}, @data={}>, @last_flush=2017-01-04 15:20:05 UTC, @flush_interval=1, @stopping=#<Concurrent::AtomicBoolean:0x705e1c24>, @buffer=[], @flush_thread=#<Thread:0x44460244 run>>", :interval=>1, :level=>:debug, :file=>"/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}←[0m
←[36mFlushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0x534d0ef1 @operations_mutex=#<Mutex:0x5d8afae8>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x59b56581>, @submit_proc=#<Proc:0x27b65f32@D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:57>, @logger=#<Cabin::Channel:0x2d61ac96 @metrics=#<Cabin::Metrics:0x5f8a5dd6 @metrics_lock=#<Mutex:0x7c980f9c>, @metrics={}, @channel=#<Cabin::Channel:0x2d61ac96 ...>>, @subscriber_lock=#<Mutex:0x69c280f2>, @level=:debug, @subscribers={13288=>#<Cabin::Subscriber:0x448e1447 @output=#<Cabin::Outputs::IO:0x78d617a5 @io=#<IO:fd 1>, @lock=#<Mutex:0x56edd5d>>, @options={}>}, @data={}>, @last_flush=2017-01-04 15:20:06 UTC, @flush_interval=1, @stopping=#<Concurrent::AtomicBoolean:0x705e1c24>, @buffer=[], @flush_thread=#<Thread:0x44460244 run>>", :interval=>1, :level=>:debug, :file=>"/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}←[0m
←[36mPushing flush onto pipeline {:level=>:debug, :file=>"/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb", :line=>"458", :method=>"flush"}←[0m
←[36mFlushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:0x534d0ef1 @operations_mutex=#<Mutex:0x5d8afae8>, @max_size=500, @operations_lock=#<Java::JavaUtilConcurrentLocks::ReentrantLock:0x59b56581>, @submit_proc=#<Proc:0x27b65f32@D:/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:57>, @logger=#<Cabin::Channel:0x2d61ac96 @metrics=#<Cabin::Metrics:0x5f8a5dd6 @metrics_lock=#<Mutex:0x7c980f9c>, @metrics={}, @channel=#<Cabin::Channel:0x2d61ac96 ...>>, @subscriber_lock=#<Mutex:0x69c280f2>, @level=:debug, @subscribers={13288=>#<Cabin::Subscriber:0x448e1447 @output=#<Cabin::Outputs::IO:0x78d617a5 @io=#<IO:fd 1>, @lock=#<Mutex:0x56edd5d>>, @options={}>}, @data={}>, @last_flush=2017-01-04 15:20:07 UTC, @flush_interval=1, @stopping=#<Concurrent::AtomicBoolean:0x705e1c24>, @buffer=[], @flush_thread=#<Thread:0x44460244 run>>", :interval=>1, :level=>:debug, :file=>"/wsroot/logstash-2.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/buffer.rb", :line=>"90", :method=>"interval_flush"}←[0m

Thanks and KR!
Ruth

**Comment by elirei72** [comment]
I don't think SNMP v3 will be supported with any ruby implimentation soon. I was looking for SNMP v3 trap support for Sensu but the following issues show it's not a huge priority for the ruby community. 

https://github.com/hallidave/ruby-snmp/issues/2 
https://github.com/sensu-plugins/sensu-plugins-snmp/issues/13

**Comment by zjcnew** [comment]
@abiruth84 Do you to solve it? and now I have encountered such a problem!

**Comment by josdotso** [comment]
Looking for this too. Any updates?

**Comment by jaebongim** [comment]
I am looking for this tot. Any update or schedule?

**Comment by chugh-rahul** [comment]
+1

**Comment by niempy** [comment]
+1

**Comment by alxdembo** [comment]
+1

**Comment by tjakobsen90** [comment]
+1

**Comment by fabriciodelocco** [comment]
+1

**Comment by MrPippin66** [comment]
+1 as well.

Some info sent in SNMP traps is considered sensitive and needs to be encrypted over the wire

**Comment by 09nimit** [comment]
+1

**Comment by swtrux** [comment]
V3 support for traps is needed badly and also the ability to receive SNMP Inform messages.

**Comment by stevie-sy** [comment]
+1 as well. 
For security reasons we also need to send v3 instead of v1/v2 traps.

**Comment by phil-or** [comment]
+1

**Comment by summerpeh** [comment]
+1

**Comment by siddharth4u12** [comment]
+1 need this please

**Comment by maheshacc** [comment]
+1 Will this be supported anytime soon?

**Comment by gourounaki** [comment]
+1

**Comment by Sandfish** [comment]
+1

**Comment by fadecore** [comment]
Coming back after 6 years, notice to myself: there is a rubygem with snmpv3 support  https://github.com/swisscom/ruby-netsnmp. Check of Integration ist easier both fluentd

**Comment by melgawad** [comment]
Is there any update if there is not, what is the plan to implement SNMP V3 in the SNMP trap input plugin?

**Comment by Erikg346** [comment]
+1

**Comment by gsymeoni** [comment]
+1
